// <auto-generated>
//     Generated by tools/generate_avx512_montgomery_kernel.py. Do not edit by hand.
//     To regenerate, run from the repository root:
//         python tools/generate_avx512_montgomery_kernel.py
// </auto-generated>

using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;

namespace ElectionGuard.Core.Crypto;

internal sealed partial class Avx512Montgomery
{
    /// <summary>The vector count this kernel was generated for; must equal <see cref="Vectors"/>.</summary>
    private const int GeneratedVectors = 18;

    /// <summary>
    /// The body of <see cref="Multiply"/>, with the accumulator unrolled into named locals so that
    /// it can stay in registers. See the class remarks for the algorithm and its bounds.
    /// </summary>
    [MethodImpl(MethodImplOptions.NoInlining)]
    private void MultiplyCore(ref ulong a, ref ulong b, ref ulong result)
    {
        ref Vector512<ulong> va = ref Unsafe.As<ulong, Vector512<ulong>>(ref a);
        ref Vector512<ulong> vm = ref Unsafe.As<ulong, Vector512<ulong>>(ref _modulusDigits[0]);
        ulong a0 = a;
        ulong m0 = _modulusDigits[0];
        ulong k0 = _k0;
        Vector512<ulong> zero = Vector512<ulong>.Zero;
        Vector512<ulong> mask = Vector512.Create(DigitMask);

        // The accumulator, digit 8k + j in lane j of xk.
        Vector512<ulong> x0 = zero;
        Vector512<ulong> x1 = zero;
        Vector512<ulong> x2 = zero;
        Vector512<ulong> x3 = zero;
        Vector512<ulong> x4 = zero;
        Vector512<ulong> x5 = zero;
        Vector512<ulong> x6 = zero;
        Vector512<ulong> x7 = zero;
        Vector512<ulong> x8 = zero;
        Vector512<ulong> x9 = zero;
        Vector512<ulong> x10 = zero;
        Vector512<ulong> x11 = zero;
        Vector512<ulong> x12 = zero;
        Vector512<ulong> x13 = zero;
        Vector512<ulong> x14 = zero;
        Vector512<ulong> x15 = zero;
        Vector512<ulong> x16 = zero;
        Vector512<ulong> x17 = zero;

        int i = 0;
        for (int block = 0; block < Iterations; block += NormalizeInterval)
        {
            int end = Math.Min(block + NormalizeInterval, Iterations);
            for (; i < end; i++)
            {
                // y makes the bottom digit of acc + a*b[i] + y*p divisible by 2^DigitBits, so the
                // whole sum can be shifted down one digit. That bottom digit's high part is the
                // carry, computed here in scalar because the shift discards lane 0.
                ulong bi = Unsafe.Add(ref b, i);
                ulong t0 = x0.ToScalar() + a0 * bi;
                ulong y = unchecked(t0 * k0) & DigitMask;
                ulong carry = (t0 + y * m0) >> DigitBits;
                Vector512<uint> vb = Vector512.Create(bi).AsUInt32();
                Vector512<uint> vy = Vector512.Create(y).AsUInt32();

                // acc += a * b[i] + p * y, each lane a 32x32->64-bit product of two digits.
                Vector512<ulong> s0 = Avx512F.Add(Avx512F.Add(x0, Avx512F.Multiply(Unsafe.Add(ref va, 0).AsUInt32(), vb)), Avx512F.Multiply(Unsafe.Add(ref vm, 0).AsUInt32(), vy));
                Vector512<ulong> s1 = Avx512F.Add(Avx512F.Add(x1, Avx512F.Multiply(Unsafe.Add(ref va, 1).AsUInt32(), vb)), Avx512F.Multiply(Unsafe.Add(ref vm, 1).AsUInt32(), vy));
                Vector512<ulong> s2 = Avx512F.Add(Avx512F.Add(x2, Avx512F.Multiply(Unsafe.Add(ref va, 2).AsUInt32(), vb)), Avx512F.Multiply(Unsafe.Add(ref vm, 2).AsUInt32(), vy));
                Vector512<ulong> s3 = Avx512F.Add(Avx512F.Add(x3, Avx512F.Multiply(Unsafe.Add(ref va, 3).AsUInt32(), vb)), Avx512F.Multiply(Unsafe.Add(ref vm, 3).AsUInt32(), vy));
                Vector512<ulong> s4 = Avx512F.Add(Avx512F.Add(x4, Avx512F.Multiply(Unsafe.Add(ref va, 4).AsUInt32(), vb)), Avx512F.Multiply(Unsafe.Add(ref vm, 4).AsUInt32(), vy));
                Vector512<ulong> s5 = Avx512F.Add(Avx512F.Add(x5, Avx512F.Multiply(Unsafe.Add(ref va, 5).AsUInt32(), vb)), Avx512F.Multiply(Unsafe.Add(ref vm, 5).AsUInt32(), vy));
                Vector512<ulong> s6 = Avx512F.Add(Avx512F.Add(x6, Avx512F.Multiply(Unsafe.Add(ref va, 6).AsUInt32(), vb)), Avx512F.Multiply(Unsafe.Add(ref vm, 6).AsUInt32(), vy));
                Vector512<ulong> s7 = Avx512F.Add(Avx512F.Add(x7, Avx512F.Multiply(Unsafe.Add(ref va, 7).AsUInt32(), vb)), Avx512F.Multiply(Unsafe.Add(ref vm, 7).AsUInt32(), vy));
                Vector512<ulong> s8 = Avx512F.Add(Avx512F.Add(x8, Avx512F.Multiply(Unsafe.Add(ref va, 8).AsUInt32(), vb)), Avx512F.Multiply(Unsafe.Add(ref vm, 8).AsUInt32(), vy));
                Vector512<ulong> s9 = Avx512F.Add(Avx512F.Add(x9, Avx512F.Multiply(Unsafe.Add(ref va, 9).AsUInt32(), vb)), Avx512F.Multiply(Unsafe.Add(ref vm, 9).AsUInt32(), vy));
                Vector512<ulong> s10 = Avx512F.Add(Avx512F.Add(x10, Avx512F.Multiply(Unsafe.Add(ref va, 10).AsUInt32(), vb)), Avx512F.Multiply(Unsafe.Add(ref vm, 10).AsUInt32(), vy));
                Vector512<ulong> s11 = Avx512F.Add(Avx512F.Add(x11, Avx512F.Multiply(Unsafe.Add(ref va, 11).AsUInt32(), vb)), Avx512F.Multiply(Unsafe.Add(ref vm, 11).AsUInt32(), vy));
                Vector512<ulong> s12 = Avx512F.Add(Avx512F.Add(x12, Avx512F.Multiply(Unsafe.Add(ref va, 12).AsUInt32(), vb)), Avx512F.Multiply(Unsafe.Add(ref vm, 12).AsUInt32(), vy));
                Vector512<ulong> s13 = Avx512F.Add(Avx512F.Add(x13, Avx512F.Multiply(Unsafe.Add(ref va, 13).AsUInt32(), vb)), Avx512F.Multiply(Unsafe.Add(ref vm, 13).AsUInt32(), vy));
                Vector512<ulong> s14 = Avx512F.Add(Avx512F.Add(x14, Avx512F.Multiply(Unsafe.Add(ref va, 14).AsUInt32(), vb)), Avx512F.Multiply(Unsafe.Add(ref vm, 14).AsUInt32(), vy));
                Vector512<ulong> s15 = Avx512F.Add(Avx512F.Add(x15, Avx512F.Multiply(Unsafe.Add(ref va, 15).AsUInt32(), vb)), Avx512F.Multiply(Unsafe.Add(ref vm, 15).AsUInt32(), vy));
                Vector512<ulong> s16 = Avx512F.Add(Avx512F.Add(x16, Avx512F.Multiply(Unsafe.Add(ref va, 16).AsUInt32(), vb)), Avx512F.Multiply(Unsafe.Add(ref vm, 16).AsUInt32(), vy));
                Vector512<ulong> s17 = Avx512F.Add(Avx512F.Add(x17, Avx512F.Multiply(Unsafe.Add(ref va, 17).AsUInt32(), vb)), Avx512F.Multiply(Unsafe.Add(ref vm, 17).AsUInt32(), vy));

                // acc >>= DigitBits: every lane moves down one, and the top lane fills with zero.
                x0 = Avx512F.AlignRight64(s1, s0, 1);
                x1 = Avx512F.AlignRight64(s2, s1, 1);
                x2 = Avx512F.AlignRight64(s3, s2, 1);
                x3 = Avx512F.AlignRight64(s4, s3, 1);
                x4 = Avx512F.AlignRight64(s5, s4, 1);
                x5 = Avx512F.AlignRight64(s6, s5, 1);
                x6 = Avx512F.AlignRight64(s7, s6, 1);
                x7 = Avx512F.AlignRight64(s8, s7, 1);
                x8 = Avx512F.AlignRight64(s9, s8, 1);
                x9 = Avx512F.AlignRight64(s10, s9, 1);
                x10 = Avx512F.AlignRight64(s11, s10, 1);
                x11 = Avx512F.AlignRight64(s12, s11, 1);
                x12 = Avx512F.AlignRight64(s13, s12, 1);
                x13 = Avx512F.AlignRight64(s14, s13, 1);
                x14 = Avx512F.AlignRight64(s15, s14, 1);
                x15 = Avx512F.AlignRight64(s16, s15, 1);
                x16 = Avx512F.AlignRight64(s17, s16, 1);
                x17 = Avx512F.AlignRight64(zero, s17, 1);
                x0 = Avx512F.Add(x0, Vector512.CreateScalar(carry));
            }

            // One carry step for every lane at once: lane k keeps its low DigitBits bits and gains
            // lane k-1's high bits.
            Vector512<ulong> h0 = Avx512F.ShiftRightLogical(x0, DigitBits);
            Vector512<ulong> h1 = Avx512F.ShiftRightLogical(x1, DigitBits);
            Vector512<ulong> h2 = Avx512F.ShiftRightLogical(x2, DigitBits);
            Vector512<ulong> h3 = Avx512F.ShiftRightLogical(x3, DigitBits);
            Vector512<ulong> h4 = Avx512F.ShiftRightLogical(x4, DigitBits);
            Vector512<ulong> h5 = Avx512F.ShiftRightLogical(x5, DigitBits);
            Vector512<ulong> h6 = Avx512F.ShiftRightLogical(x6, DigitBits);
            Vector512<ulong> h7 = Avx512F.ShiftRightLogical(x7, DigitBits);
            Vector512<ulong> h8 = Avx512F.ShiftRightLogical(x8, DigitBits);
            Vector512<ulong> h9 = Avx512F.ShiftRightLogical(x9, DigitBits);
            Vector512<ulong> h10 = Avx512F.ShiftRightLogical(x10, DigitBits);
            Vector512<ulong> h11 = Avx512F.ShiftRightLogical(x11, DigitBits);
            Vector512<ulong> h12 = Avx512F.ShiftRightLogical(x12, DigitBits);
            Vector512<ulong> h13 = Avx512F.ShiftRightLogical(x13, DigitBits);
            Vector512<ulong> h14 = Avx512F.ShiftRightLogical(x14, DigitBits);
            Vector512<ulong> h15 = Avx512F.ShiftRightLogical(x15, DigitBits);
            Vector512<ulong> h16 = Avx512F.ShiftRightLogical(x16, DigitBits);
            Vector512<ulong> h17 = Avx512F.ShiftRightLogical(x17, DigitBits);
            x0 = Avx512F.Add(Avx512F.And(x0, mask), Avx512F.AlignRight64(h0, zero, 7));
            x1 = Avx512F.Add(Avx512F.And(x1, mask), Avx512F.AlignRight64(h1, h0, 7));
            x2 = Avx512F.Add(Avx512F.And(x2, mask), Avx512F.AlignRight64(h2, h1, 7));
            x3 = Avx512F.Add(Avx512F.And(x3, mask), Avx512F.AlignRight64(h3, h2, 7));
            x4 = Avx512F.Add(Avx512F.And(x4, mask), Avx512F.AlignRight64(h4, h3, 7));
            x5 = Avx512F.Add(Avx512F.And(x5, mask), Avx512F.AlignRight64(h5, h4, 7));
            x6 = Avx512F.Add(Avx512F.And(x6, mask), Avx512F.AlignRight64(h6, h5, 7));
            x7 = Avx512F.Add(Avx512F.And(x7, mask), Avx512F.AlignRight64(h7, h6, 7));
            x8 = Avx512F.Add(Avx512F.And(x8, mask), Avx512F.AlignRight64(h8, h7, 7));
            x9 = Avx512F.Add(Avx512F.And(x9, mask), Avx512F.AlignRight64(h9, h8, 7));
            x10 = Avx512F.Add(Avx512F.And(x10, mask), Avx512F.AlignRight64(h10, h9, 7));
            x11 = Avx512F.Add(Avx512F.And(x11, mask), Avx512F.AlignRight64(h11, h10, 7));
            x12 = Avx512F.Add(Avx512F.And(x12, mask), Avx512F.AlignRight64(h12, h11, 7));
            x13 = Avx512F.Add(Avx512F.And(x13, mask), Avx512F.AlignRight64(h13, h12, 7));
            x14 = Avx512F.Add(Avx512F.And(x14, mask), Avx512F.AlignRight64(h14, h13, 7));
            x15 = Avx512F.Add(Avx512F.And(x15, mask), Avx512F.AlignRight64(h15, h14, 7));
            x16 = Avx512F.Add(Avx512F.And(x16, mask), Avx512F.AlignRight64(h16, h15, 7));
            x17 = Avx512F.Add(Avx512F.And(x17, mask), Avx512F.AlignRight64(h17, h16, 7));
        }

        // a and b are not read again, so writing the result now is safe even when it aliases them.
        ref Vector512<ulong> vr = ref Unsafe.As<ulong, Vector512<ulong>>(ref result);
        Unsafe.Add(ref vr, 0) = x0;
        Unsafe.Add(ref vr, 1) = x1;
        Unsafe.Add(ref vr, 2) = x2;
        Unsafe.Add(ref vr, 3) = x3;
        Unsafe.Add(ref vr, 4) = x4;
        Unsafe.Add(ref vr, 5) = x5;
        Unsafe.Add(ref vr, 6) = x6;
        Unsafe.Add(ref vr, 7) = x7;
        Unsafe.Add(ref vr, 8) = x8;
        Unsafe.Add(ref vr, 9) = x9;
        Unsafe.Add(ref vr, 10) = x10;
        Unsafe.Add(ref vr, 11) = x11;
        Unsafe.Add(ref vr, 12) = x12;
        Unsafe.Add(ref vr, 13) = x13;
        Unsafe.Add(ref vr, 14) = x14;
        Unsafe.Add(ref vr, 15) = x15;
        Unsafe.Add(ref vr, 16) = x16;
        Unsafe.Add(ref vr, 17) = x17;

        PropagateCarries(ref result);
    }
}
