using ElectionGuard.Core.Models;
using System.Diagnostics;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics.X86;

namespace ElectionGuard.Core.Crypto;

/// <summary>
/// Montgomery multiplication mod p on AVX-512F, for the exponentiations that have no precomputed
/// table: the x^q subgroup checks of Verifications 2, 6 and 7, and any base other than g, K or K-hat.
/// Note 3.5. <see cref="MontgomeryContext"/> is the scalar equivalent, and the fallback whenever
/// <see cref="Avx512F"/> is unavailable or p does not fit; <see cref="MontgomeryModP"/> and
/// <see cref="SubgroupMembership"/> choose between the two.
///
/// This is the "almost Montgomery multiplication" of Gueron and Krasnov ("Software implementation
/// of modular exponentiation, using advanced vector instructions architectures", 2012), on 52-bit
/// digits as their AVX-512 IFMA version uses, but with the 52 x 52 -&gt; 104-bit digit products
/// computed by double-precision fused multiply-adds instead of IFMA, which .NET does not expose.
/// Splitting an exact product into floating-point halves this way is the technique of Emmart,
/// Zheng and Weems ("Faster Modular Exponentiation Using Double Precision Floating Point Arithmetic
/// on the GPU", ARITH 2018):
///
/// 1. A value is held as <see cref="Lanes"/> = 80 digits of <see cref="DigitBits"/> = 52 bits, one
///    per 64-bit lane, so 10 Vector512 registers. Every digit below 2^52 is exactly a double.
/// 2. Each of the <see cref="Iterations"/> steps adds a * b[i] + y * p to the accumulator, with the
///    digit y chosen so the bottom digit becomes zero, and shifts it down one digit. That is
///    Montgomery reduction one 52-bit digit at a time, with R = 2^(52 * 79) = 2^4108.
/// 3. The lanes are fully carried, one at a time, only at the end.
///
/// The digit products. For digits u, v below 2^52, u * v is below 2^104, so u * v + 2^104 lies in
/// [2^104, 2^105), where doubles are spaced 2^52 apart. Rounding that sum toward negative infinity,
/// which AVX-512 encodes per instruction, gives h = 2^104 + hi * 2^52 with hi = floor(u * v / 2^52)
/// exactly. Then (2^104 + 2^52) - h = (1 - hi) * 2^52 is representable, so that subtraction is exact,
/// and u * v + (1 - hi) * 2^52 = lo + 2^52 with lo = u * v mod 2^52 lies in [2^52, 2^53), where
/// doubles are the integers: that fused multiply-add is exact too. So three floating-point
/// instructions split the product with no rounding error, and both halves are non-negative.
///
/// Neither half is converted back to an integer. A double in a fixed binade is its integer value
/// plus a constant when its bits are read as an integer: h reads as <see cref="HighBias"/> + hi and
/// lo + 2^52 as <see cref="LowBias"/> + lo. The kernel adds those bit patterns into the accumulator
/// as they are; the biases are the same in every lane on every step, independent of the operands, so
/// lane 0's is tracked in scalar wherever its true value is needed and the total is subtracted once,
/// at the end (<see cref="FinalBias"/>). Wrapping mod 2^64 along the way loses nothing.
///
/// The "almost" is that there is no final conditional subtraction. Because R &gt; 4p, inputs in
/// [0, 2p) give an output in [0, 2p): (a * b + Y * p) / R &lt; (4p^2 + R * p) / R &lt; 2p. So a value
/// stays in [0, 2p) through an entire exponentiation, never fully reduced, and is brought into
/// [0, p) only once, on the way out. The representation is redundant - a residue x may be held as
/// x or x + p - which is why <see cref="IsOne"/> exists rather than comparing digits with
/// <see cref="One"/>.
///
/// Lane bounds. Each step adds to a lane two low halves and two high halves, each below 2^52, so
/// under 2^54, and lane 0 also gains the carry out of the digit below, which is under 2^10. Lanes
/// shift down as they go and the accumulator starts at zero, so across all 79 steps a lane's true
/// value stays below 79 * 2^54 + 2^10 &lt; 2^61. Nothing needs normalizing until the end.
///
/// The operation count does not depend on the operands: the loop runs a fixed number of times and
/// has no data-dependent branches, so <see cref="PowMontgomeryInto"/> keeps the uniform operation
/// count of the scalar exponentiation it replaces. The floating-point operands are integers or zero,
/// never subnormal, so the instructions' timing does not depend on them either.
///
/// An instance is immutable data for one modulus and safe to share across threads; every working
/// buffer is on the caller's stack. Verification runs many of these in parallel.
///
/// The multiplication itself is in Avx512Montgomery.Kernel.g.cs, generated by
/// tools/generate_avx512_montgomery_kernel.py: the accumulator is unrolled into 10 named locals so
/// the JIT can keep it in registers rather than reloading it every step. Measured on a Zen 4 core,
/// a multiply takes about 1.1 us, against 1.9 us for the earlier version of this engine on 29-bit
/// digits and vpmuludq, which needed 142 steps over 18 vectors.
/// </summary>
internal sealed partial class Avx512Montgomery
{
    internal const int DigitBits = 52;

    internal const ulong DigitMask = (1UL << DigitBits) - 1;

    /// <summary>Reduction steps per multiplication; R = 2^(DigitBits * Iterations) = 2^4108 &gt; 4p.</summary>
    internal const int Iterations = 79;

    /// <summary>
    /// Digits per value: <see cref="Iterations"/> rounded up to a whole number of vectors. The top
    /// lane is headroom for the accumulator.
    /// </summary>
    internal const int Lanes = 80;

    internal const int Vectors = Lanes / 8;

    /// <summary>Largest modulus this engine handles. 4p must stay below R = 2^4108.</summary>
    internal const int MaxModulusBits = 4096;

    /// <summary>2^52, the binade in which doubles are exactly the integers [2^52, 2^53).</summary>
    internal const double TwoPow52 = 4503599627370496.0;

    /// <summary>2^104, the addend that puts a digit product's high half in a binade of spacing 2^52.</summary>
    internal const double TwoPow104 = 20282409603651670423947251286016.0;

    /// <summary>The bits of 2^52 read as an integer: a double in [2^52, 2^53) reads as this plus its offset from 2^52.</summary>
    internal const ulong LowBias = 0x4330_0000_0000_0000;

    /// <summary>The bits of 2^104: a double in [2^104, 2^105) reads as this plus its offset from 2^104 in units of 2^52.</summary>
    internal const ulong HighBias = 0x4670_0000_0000_0000;

    /// <summary>What one step adds to the bias of every lane but the top one: two high halves and two low halves.</summary>
    internal const ulong IterationBias = unchecked(2 * HighBias + 2 * LowBias);

    /// <summary>Fails compilation if the generated kernel was produced for a different vector count.</summary>
    private const int GeneratedKernelMatches = 1 / (GeneratedVectors == Vectors ? 1 : 0);

    private const int LimbsForDigits = (DigitBits * Lanes + 63) / 64 + 1;

    /// <summary>
    /// The bias each accumulator lane carries after the last step, subtracted to recover its true
    /// value. Lane k after step i + 1 holds lane k + 1's sum from step i, which picked up two low
    /// halves, plus two high halves; the top lane starts each step from zero and gains only the high
    /// halves. The recurrence runs the same way for every multiplication, so it is evaluated once.
    /// </summary>
    internal static readonly ulong[] FinalBias = ComputeFinalBias();

    private readonly ulong[] _modulusDigits;
    private readonly double[] _modulusDoubles;
    private readonly ulong _k0;
    private readonly ulong[] _rSquared;
    private readonly ulong[] _one;
    private readonly ulong[] _onePlusModulus;

    private Avx512Montgomery(BigInteger modulus)
    {
        if (!Fits(modulus))
        {
            throw new ArgumentException($"AVX-512 Montgomery arithmetic requires an odd modulus of at most {MaxModulusBits} bits.", nameof(modulus));
        }

        Modulus = modulus;
        _modulusDigits = ToDigits(modulus);
        _modulusDoubles = new double[Lanes];
        for (int k = 0; k < Lanes; k++)
        {
            _modulusDoubles[k] = _modulusDigits[k];
        }

        // k0 = -p^-1 mod 2^52: Hensel lifting mod 2^64, as in MontgomeryContext, then truncated. For
        // the spec's p, whose low 256 bits are all ones, it is 1.
        ulong p0 = (ulong)(modulus & ulong.MaxValue);
        ulong inverse = 1;
        for (int i = 0; i < 6; i++)
        {
            inverse = unchecked(inverse * (2 - p0 * inverse));
        }
        _k0 = unchecked(0UL - inverse) & DigitMask;

        BigInteger rModP = (BigInteger.One << (DigitBits * Iterations)) % modulus;
        _rSquared = ToDigits(rModP * rModP % modulus);
        _one = ToDigits(rModP);
        _onePlusModulus = ToDigits(rModP + modulus);
    }

    private static ulong[] ComputeFinalBias()
    {
        ulong[] bias = new ulong[Lanes];
        ulong[] next = new ulong[Lanes];
        for (int i = 0; i < Iterations; i++)
        {
            for (int k = 0; k < Lanes - 1; k++)
            {
                next[k] = unchecked(bias[k + 1] + IterationBias);
            }
            next[Lanes - 1] = unchecked(2 * HighBias);
            (bias, next) = (next, bias);
        }

        return bias;
    }

    /// <summary>Whether the hardware has the instructions this engine needs.</summary>
    internal static bool IsSupported => Avx512F.IsSupported;

    /// <summary>The modulus this instance was built for.</summary>
    internal BigInteger Modulus { get; }

    /// <summary>Montgomery form of 1, R mod p. A product may also hold it as R mod p + p; see <see cref="IsOne"/>.</summary>
    internal ReadOnlySpan<ulong> One => _one;

    private static Avx512Montgomery? _cached;

    /// <summary>Whether <paramref name="modulus"/> is one this engine can work with.</summary>
    internal static bool Fits(BigInteger modulus)
    {
        return modulus > 1 && !modulus.IsEven && modulus.GetBitLength() <= MaxModulusBits;
    }

    /// <summary>
    /// The engine for the currently active election parameters, or false when the hardware lacks
    /// AVX-512F or p does not fit, in which case the caller uses <see cref="MontgomeryContext"/>.
    /// Rebuilt only when <see cref="EGParameters"/> is pointed at a different p.
    /// </summary>
    internal static bool TryGetCurrent(out Avx512Montgomery engine)
    {
        engine = null!;
        if (!IsSupported)
        {
            return false;
        }

        BigInteger p = EGParameters.P;
        Avx512Montgomery? cached = _cached;
        if (cached is not null && cached.Modulus == p)
        {
            engine = cached;
            return true;
        }

        if (!Fits(p))
        {
            return false;
        }

        cached = new Avx512Montgomery(p);
        _cached = cached;
        engine = cached;
        return true;
    }

    /// <summary>
    /// Almost-Montgomery multiplication: result = a * b * R^-1 mod p, possibly plus p.
    ///
    /// Both operands must be digit vectors of at least <see cref="Lanes"/> digits, each digit below
    /// 2^52, holding values below 2p. The result is the same shape. <paramref name="result"/> may
    /// alias either operand, which makes squaring in place safe.
    /// </summary>
    internal void Multiply(ReadOnlySpan<ulong> a, ReadOnlySpan<ulong> b, Span<ulong> result)
    {
        if (!Avx512F.IsSupported)
        {
            throw new PlatformNotSupportedException("AVX-512F is not available.");
        }

        if (a.Length < Lanes || b.Length < Lanes || result.Length < Lanes)
        {
            throw new ArgumentException($"Operands must have at least {Lanes} digits.");
        }

        // A digit of 2^52 or more is not exactly a double's mantissa and breaks the exactness the
        // kernel rests on, silently. Every value this engine produces is fully carried.
        Debug.Assert(IsFullyCarried(a) && IsFullyCarried(b), "Operand digits must be below 2^52.");

        MultiplyCore(ref Unsafe.AsRef(in a[0]), ref Unsafe.AsRef(in b[0]), ref result[0]);
    }

    /// <summary>Converts a value in [0, p) to Montgomery form, value * R mod p (possibly plus p).</summary>
    internal void ToMontgomery(BigInteger value, Span<ulong> result)
    {
        Span<ulong> plain = stackalloc ulong[Lanes];
        WriteDigits(value, plain);

        // value * R^2 * R^-1 = value * R.
        Multiply(plain, _rSquared, result);
    }

    /// <summary>Converts a Montgomery-form value in [0, 2p) back to an ordinary residue in [0, p).</summary>
    internal BigInteger FromMontgomery(ReadOnlySpan<ulong> montgomery)
    {
        Span<ulong> plain = stackalloc ulong[Lanes];
        Span<ulong> one = stackalloc ulong[Lanes];
        one.Clear();
        one[0] = 1;

        // x * 1 * R^-1. With b = 1 the bound tightens to (x + Y * p) / R < 2p / R + p, so the result
        // is at most p, and equal to p exactly when x is a multiple of p. Checking that here, in
        // digits, saves allocating a second BigInteger for the subtraction.
        Multiply(montgomery, one, plain);
        if (plain.SequenceEqual(_modulusDigits))
        {
            return BigInteger.Zero;
        }

        return FromDigits(plain);
    }

    /// <summary>
    /// Writes a Montgomery-form value in [0, 2p), converted back to an ordinary residue in [0, p), as
    /// the fixed-width big-endian bytes <see cref="IntegerModP.ToByteArray"/> would produce for it,
    /// without building a BigInteger. The same conversion as <see cref="FromMontgomery"/>, including
    /// its one subtlety: a multiple of p comes out of the multiply as p itself and must be written as 0.
    /// </summary>
    internal void WriteBigEndian(ReadOnlySpan<ulong> montgomery, Span<byte> destination)
    {
        Span<ulong> plain = stackalloc ulong[Lanes];
        Span<ulong> one = stackalloc ulong[Lanes];
        one.Clear();
        one[0] = 1;

        Multiply(montgomery, one, plain);
        if (plain.SequenceEqual(_modulusDigits))
        {
            destination.Clear();
            return;
        }

        Span<ulong> limbs = stackalloc ulong[LimbsForDigits];
        DigitsToLimbs(plain, limbs);
        MontgomeryContext.WriteLimbsBigEndian(limbs, destination);
    }

    /// <summary>
    /// Whether a Montgomery-form value in [0, 2p) represents 1. The representation is redundant, so
    /// that is either R mod p or R mod p + p; fully carried digits are unique, so comparing digits
    /// is exact.
    /// </summary>
    internal bool IsOne(ReadOnlySpan<ulong> montgomery)
    {
        ReadOnlySpan<ulong> digits = montgomery[..Lanes];
        return digits.SequenceEqual(_one) || digits.SequenceEqual(_onePlusModulus);
    }

    /// <summary>
    /// basis^exponent mod p, with <paramref name="basis"/> in [0, p), leaving the Montgomery-form
    /// result in <paramref name="result"/>. See <see cref="PowMontgomeryInto"/>.
    /// </summary>
    internal void PowInto(BigInteger basis, ReadOnlySpan<byte> exponentBigEndian, Span<ulong> result)
    {
        Span<ulong> montgomeryBasis = stackalloc ulong[Lanes];
        ToMontgomery(basis, montgomeryBasis);
        PowMontgomeryInto(montgomeryBasis, exponentBigEndian, result);
    }

    /// <summary>
    /// The same table-free windowed square-and-multiply as
    /// <see cref="MontgomeryModP.PowMontgomeryInto"/>, with the same window widths and the same
    /// exponent-independent operation count: every window performs its squarings and its multiply,
    /// including when its digit is zero, and leading zero digits are not skipped, because this also
    /// runs with secret nonces as exponents. Window lookups are indexed by exponent digits, as there.
    ///
    /// There is no dedicated squaring: the products are vectorized across digits, so a square has
    /// no cross products to share. Every intermediate value stays in [0, 2p); the result is in
    /// Montgomery form and in [0, 2p), for <see cref="FromMontgomery"/> or <see cref="IsOne"/>.
    /// </summary>
    internal void PowMontgomeryInto(ReadOnlySpan<ulong> montgomeryBasis, ReadOnlySpan<byte> exponentBigEndian, Span<ulong> result)
    {
        // Both widths divide 8, so a byte always splits into a whole number of windows.
        int windowBits = exponentBigEndian.Length <= MontgomeryModP.NarrowWindowMaxExponentBytes
            ? MontgomeryModP.NarrowWindowBits
            : MontgomeryModP.TableFreeWindowBits;
        int windowSize = 1 << windowBits;
        int windowsPerByte = 8 / windowBits;

        // window[i] = basis^i in Montgomery form. 18 KB, on the stack so that the exponentiation
        // allocates nothing.
        Span<ulong> window = stackalloc ulong[(1 << MontgomeryModP.TableFreeWindowBits) * Lanes];
        _one.CopyTo(window[..Lanes]);
        montgomeryBasis[..Lanes].CopyTo(window.Slice(Lanes, Lanes));
        for (int i = 2; i < windowSize; i++)
        {
            Multiply(window.Slice((i - 1) * Lanes, Lanes), window.Slice(Lanes, Lanes), window.Slice(i * Lanes, Lanes));
        }

        Span<ulong> accumulator = stackalloc ulong[Lanes];
        _one.CopyTo(accumulator);

        for (int i = 0; i < exponentBigEndian.Length; i++)
        {
            byte current = exponentBigEndian[i];

            // Most significant window of the byte first.
            for (int w = 0; w < windowsPerByte; w++)
            {
                int shift = 8 - windowBits * (w + 1);
                int digit = (current >> shift) & (windowSize - 1);

                for (int square = 0; square < windowBits; square++)
                {
                    Multiply(accumulator, accumulator, accumulator);
                }

                Multiply(accumulator, window.Slice(digit * Lanes, Lanes), accumulator);
            }
        }

        accumulator.CopyTo(result);
    }

    /// <summary>Whether every one of the first <see cref="Lanes"/> digits is below 2^52, for assertions.</summary>
    private static bool IsFullyCarried(ReadOnlySpan<ulong> digits)
    {
        foreach (ulong digit in digits[..Lanes])
        {
            if (digit > DigitMask)
            {
                return false;
            }
        }

        return true;
    }

    /// <summary>
    /// The final, sequential carry pass of a multiplication: every lane is reduced to a 52-bit digit
    /// and its excess added to the next. The lanes are below 2^61 once their biases are removed, so
    /// nothing overflows, and the value is below 2p, so nothing carries out of the top lane.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PropagateCarries(ref ulong lanes)
    {
        ulong carry = 0;
        for (int k = 0; k < Lanes; k++)
        {
            ulong value = Unsafe.Add(ref lanes, k) + carry;
            Unsafe.Add(ref lanes, k) = value & DigitMask;
            carry = value >> DigitBits;
        }
    }

    private static ulong[] ToDigits(BigInteger value)
    {
        ulong[] digits = new ulong[Lanes];
        WriteDigits(value, digits);
        return digits;
    }

    /// <summary>
    /// Writes a non-negative value below 2^(52 * 80) as <see cref="Lanes"/> 52-bit digits, least
    /// significant first, by way of the 64-bit limbs <see cref="MontgomeryContext"/> produces.
    /// </summary>
    internal static void WriteDigits(BigInteger value, Span<ulong> digits)
    {
        if (value.Sign < 0 || value.GetBitLength() > DigitBits * Lanes)
        {
            throw new ArgumentOutOfRangeException(nameof(value), "Value does not fit in the digit representation.");
        }

        Span<ulong> limbs = stackalloc ulong[LimbsForDigits];
        MontgomeryContext.WriteLimbs(value, limbs);
        for (int k = 0; k < Lanes; k++)
        {
            int bit = k * DigitBits;
            int limb = bit >> 6;
            int offset = bit & 63;
            ulong digit = limbs[limb] >> offset;
            if (offset + DigitBits > 64)
            {
                digit |= limbs[limb + 1] << (64 - offset);
            }

            digits[k] = digit & DigitMask;
        }
    }

    /// <summary>Reads a fully carried digit vector (every digit below 2^52) back as an integer.</summary>
    internal static BigInteger FromDigits(ReadOnlySpan<ulong> digits)
    {
        Span<ulong> limbs = stackalloc ulong[LimbsForDigits];
        DigitsToLimbs(digits, limbs);
        return MontgomeryContext.FromLimbs(limbs);
    }

    /// <summary>
    /// Repacks a fully carried digit vector as little-endian 64-bit limbs, into all
    /// <see cref="LimbsForDigits"/> of <paramref name="limbs"/>.
    /// </summary>
    private static void DigitsToLimbs(ReadOnlySpan<ulong> digits, Span<ulong> limbs)
    {
        limbs = limbs[..LimbsForDigits];
        limbs.Clear();
        for (int k = 0; k < Lanes; k++)
        {
            int bit = k * DigitBits;
            int limb = bit >> 6;
            int offset = bit & 63;
            ulong digit = digits[k];
            limbs[limb] |= digit << offset;
            if (offset + DigitBits > 64)
            {
                limbs[limb + 1] |= digit >> (64 - offset);
            }
        }
    }
}
