using ElectionGuard.Core.Models;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics.X86;

namespace ElectionGuard.Core.Crypto;

/// <summary>
/// Montgomery multiplication mod p on AVX-512F, for the exponentiations that have no precomputed
/// table: the x^q subgroup checks of Verifications 2, 6 and 7, and any base other than g, K or K-hat.
/// Note 3.5. <see cref="MontgomeryContext"/> is the scalar equivalent, and the fallback whenever
/// <see cref="Avx512F"/> is unavailable or p does not fit; <see cref="MontgomeryModP"/> and
/// <see cref="SubgroupMembership"/> choose between the two.
///
/// This is the "almost Montgomery multiplication" of Gueron and Krasnov ("Software implementation
/// of modular exponentiation, using advanced vector instructions architectures", 2012), adapted to
/// AVX-512F without IFMA:
///
/// 1. A value is held as <see cref="Lanes"/> = 144 digits of <see cref="DigitBits"/> = 29 bits, one
///    per 64-bit lane, so 18 Vector512 registers. The only full 64-bit multiply AVX-512F has is
///    vpmuludq, 32 x 32 -&gt; 64 bits, and 29-bit digits make each product under 2^58, leaving six
///    spare bits per lane in which carries can pile up instead of being propagated every step.
/// 2. Each of the <see cref="Iterations"/> steps adds a * b[i] + y * p to the accumulator, with the
///    digit y chosen so the bottom digit becomes zero, and shifts it down one digit. That is
///    Montgomery reduction one 29-bit digit at a time, with R = 2^(29 * 142) = 2^4118.
/// 3. Every <see cref="NormalizeInterval"/> steps each lane gives its bits above 29 to the next lane
///    up, all lanes at once. The lanes are fully carried, one at a time, only at the end.
///
/// The "almost" is that there is no final conditional subtraction. Because R &gt; 4p, inputs in
/// [0, 2p) give an output in [0, 2p): (a * b + Y * p) / R &lt; (4p^2 + R * p) / R &lt; 2p. So a value
/// stays in [0, 2p) through an entire exponentiation, never fully reduced, and is brought into
/// [0, p) only once, on the way out. The representation is redundant - a residue x may be held as
/// x or x + p - which is why <see cref="IsOne"/> exists rather than comparing digits with
/// <see cref="One"/>.
///
/// Lane bounds. After a normalization step a lane is under 2^29 plus the bits carried in from below,
/// so under 2^29 + 2^35 &lt; 2^36. Each step then adds two products under 2^58 each, and lane 0 also
/// gains a scalar carry under 2^35. Lanes shift down as they go, so over the 16 steps between
/// normalizations a lane can reach 2^36 + 16 * 2^59 + 2^35 &lt; 2^64. <see cref="NormalizeInterval"/>
/// must therefore stay at 16 or below.
///
/// The operation count does not depend on the operands: the loop runs a fixed number of times and
/// has no data-dependent branches, so <see cref="PowMontgomeryInto"/> keeps the uniform operation
/// count of the scalar exponentiation it replaces.
///
/// An instance is immutable data for one modulus and safe to share across threads; every working
/// buffer is on the caller's stack. Verification runs many of these in parallel.
///
/// The multiplication itself is in Avx512Montgomery.Kernel.g.cs, generated by
/// tools/generate_avx512_montgomery_kernel.py: the accumulator is unrolled into 18 named locals so
/// the JIT can keep it in registers rather than reloading it every step, which measured about a third
/// faster (2.3 us against 3.3 us per multiply) than the same loop over a span.
/// </summary>
internal sealed partial class Avx512Montgomery
{
    internal const int DigitBits = 29;

    internal const ulong DigitMask = (1UL << DigitBits) - 1;

    /// <summary>Reduction steps per multiplication; R = 2^(DigitBits * Iterations) = 2^4118 &gt; 4p.</summary>
    internal const int Iterations = 142;

    /// <summary>
    /// Digits per value: <see cref="Iterations"/> rounded up to a whole number of vectors. The two
    /// top lanes are headroom for values up to 2p and for the accumulator's carries.
    /// </summary>
    internal const int Lanes = 144;

    internal const int Vectors = Lanes / 8;

    /// <summary>Reduction steps between one-level normalizations. See the class remarks for the bound.</summary>
    internal const int NormalizeInterval = 16;

    /// <summary>Largest modulus this engine handles. 4p must stay below R = 2^4118.</summary>
    internal const int MaxModulusBits = 4096;

    /// <summary>Fails compilation if the generated kernel was produced for a different vector count.</summary>
    private const int GeneratedKernelMatches = 1 / (GeneratedVectors == Vectors ? 1 : 0);

    private const int LimbsForDigits = (DigitBits * Lanes + 63) / 64 + 1;

    private readonly ulong[] _modulusDigits;
    private readonly ulong _k0;
    private readonly ulong[] _rSquared;
    private readonly ulong[] _one;
    private readonly ulong[] _onePlusModulus;

    private Avx512Montgomery(BigInteger modulus)
    {
        if (!Fits(modulus))
        {
            throw new ArgumentException($"AVX-512 Montgomery arithmetic requires an odd modulus of at most {MaxModulusBits} bits.", nameof(modulus));
        }

        Modulus = modulus;
        _modulusDigits = ToDigits(modulus);

        // k0 = -p^-1 mod 2^29: Hensel lifting mod 2^64, as in MontgomeryContext, then truncated.
        ulong p0 = (ulong)(modulus & ulong.MaxValue);
        ulong inverse = 1;
        for (int i = 0; i < 6; i++)
        {
            inverse = unchecked(inverse * (2 - p0 * inverse));
        }
        _k0 = unchecked(0UL - inverse) & DigitMask;

        BigInteger rModP = (BigInteger.One << (DigitBits * Iterations)) % modulus;
        _rSquared = ToDigits(rModP * rModP % modulus);
        _one = ToDigits(rModP);
        _onePlusModulus = ToDigits(rModP + modulus);
    }

    /// <summary>Whether the hardware has the instructions this engine needs.</summary>
    internal static bool IsSupported => Avx512F.IsSupported;

    /// <summary>The modulus this instance was built for.</summary>
    internal BigInteger Modulus { get; }

    /// <summary>Montgomery form of 1, R mod p. A product may also hold it as R mod p + p; see <see cref="IsOne"/>.</summary>
    internal ReadOnlySpan<ulong> One => _one;

    private static Avx512Montgomery? _cached;

    /// <summary>Whether <paramref name="modulus"/> is one this engine can work with.</summary>
    internal static bool Fits(BigInteger modulus)
    {
        return modulus > 1 && !modulus.IsEven && modulus.GetBitLength() <= MaxModulusBits;
    }

    /// <summary>
    /// The engine for the currently active election parameters, or false when the hardware lacks
    /// AVX-512F or p does not fit, in which case the caller uses <see cref="MontgomeryContext"/>.
    /// Rebuilt only when <see cref="EGParameters"/> is pointed at a different p.
    /// </summary>
    internal static bool TryGetCurrent(out Avx512Montgomery engine)
    {
        engine = null!;
        if (!IsSupported)
        {
            return false;
        }

        BigInteger p = EGParameters.P;
        Avx512Montgomery? cached = _cached;
        if (cached is not null && cached.Modulus == p)
        {
            engine = cached;
            return true;
        }

        if (!Fits(p))
        {
            return false;
        }

        cached = new Avx512Montgomery(p);
        _cached = cached;
        engine = cached;
        return true;
    }

    /// <summary>
    /// Almost-Montgomery multiplication: result = a * b * R^-1 mod p, possibly plus p.
    ///
    /// Both operands must be digit vectors of at least <see cref="Lanes"/> digits, each digit below
    /// 2^29, holding values below 2p. The result is the same shape. <paramref name="result"/> may
    /// alias either operand, which makes squaring in place safe.
    /// </summary>
    internal void Multiply(ReadOnlySpan<ulong> a, ReadOnlySpan<ulong> b, Span<ulong> result)
    {
        if (!Avx512F.IsSupported)
        {
            throw new PlatformNotSupportedException("AVX-512F is not available.");
        }

        if (a.Length < Lanes || b.Length < Lanes || result.Length < Lanes)
        {
            throw new ArgumentException($"Operands must have at least {Lanes} digits.");
        }

        MultiplyCore(ref Unsafe.AsRef(in a[0]), ref Unsafe.AsRef(in b[0]), ref result[0]);
    }

    /// <summary>Converts a value in [0, p) to Montgomery form, value * R mod p (possibly plus p).</summary>
    internal void ToMontgomery(BigInteger value, Span<ulong> result)
    {
        Span<ulong> plain = stackalloc ulong[Lanes];
        WriteDigits(value, plain);

        // value * R^2 * R^-1 = value * R.
        Multiply(plain, _rSquared, result);
    }

    /// <summary>Converts a Montgomery-form value in [0, 2p) back to an ordinary residue in [0, p).</summary>
    internal BigInteger FromMontgomery(ReadOnlySpan<ulong> montgomery)
    {
        Span<ulong> plain = stackalloc ulong[Lanes];
        Span<ulong> one = stackalloc ulong[Lanes];
        one.Clear();
        one[0] = 1;

        // x * 1 * R^-1. With b = 1 the bound tightens to (x + Y * p) / R < 2p / R + p, so the result
        // is at most p, and equal to p exactly when x is a multiple of p. Checking that here, in
        // digits, saves allocating a second BigInteger for the subtraction.
        Multiply(montgomery, one, plain);
        if (plain.SequenceEqual(_modulusDigits))
        {
            return BigInteger.Zero;
        }

        return FromDigits(plain);
    }

    /// <summary>
    /// Whether a Montgomery-form value in [0, 2p) represents 1. The representation is redundant, so
    /// that is either R mod p or R mod p + p; fully carried digits are unique, so comparing digits
    /// is exact.
    /// </summary>
    internal bool IsOne(ReadOnlySpan<ulong> montgomery)
    {
        ReadOnlySpan<ulong> digits = montgomery[..Lanes];
        return digits.SequenceEqual(_one) || digits.SequenceEqual(_onePlusModulus);
    }

    /// <summary>
    /// basis^exponent mod p, with <paramref name="basis"/> in [0, p), leaving the Montgomery-form
    /// result in <paramref name="result"/>. See <see cref="PowMontgomeryInto"/>.
    /// </summary>
    internal void PowInto(BigInteger basis, ReadOnlySpan<byte> exponentBigEndian, Span<ulong> result)
    {
        Span<ulong> montgomeryBasis = stackalloc ulong[Lanes];
        ToMontgomery(basis, montgomeryBasis);
        PowMontgomeryInto(montgomeryBasis, exponentBigEndian, result);
    }

    /// <summary>
    /// The same table-free windowed square-and-multiply as
    /// <see cref="MontgomeryModP.PowMontgomeryInto"/>, with the same window widths and the same
    /// exponent-independent operation count: every window performs its squarings and its multiply,
    /// including when its digit is zero, and leading zero digits are not skipped, because this also
    /// runs with secret nonces as exponents. Window lookups are indexed by exponent digits, as there.
    ///
    /// There is no dedicated squaring: the products are vectorized across digits, so a square has
    /// no cross products to share. Every intermediate value stays in [0, 2p); the result is in
    /// Montgomery form and in [0, 2p), for <see cref="FromMontgomery"/> or <see cref="IsOne"/>.
    /// </summary>
    internal void PowMontgomeryInto(ReadOnlySpan<ulong> montgomeryBasis, ReadOnlySpan<byte> exponentBigEndian, Span<ulong> result)
    {
        // Both widths divide 8, so a byte always splits into a whole number of windows.
        int windowBits = exponentBigEndian.Length <= MontgomeryModP.NarrowWindowMaxExponentBytes
            ? MontgomeryModP.NarrowWindowBits
            : MontgomeryModP.TableFreeWindowBits;
        int windowSize = 1 << windowBits;
        int windowsPerByte = 8 / windowBits;

        // window[i] = basis^i in Montgomery form. 18 KB, on the stack so that the exponentiation
        // allocates nothing.
        Span<ulong> window = stackalloc ulong[(1 << MontgomeryModP.TableFreeWindowBits) * Lanes];
        _one.CopyTo(window[..Lanes]);
        montgomeryBasis[..Lanes].CopyTo(window.Slice(Lanes, Lanes));
        for (int i = 2; i < windowSize; i++)
        {
            Multiply(window.Slice((i - 1) * Lanes, Lanes), window.Slice(Lanes, Lanes), window.Slice(i * Lanes, Lanes));
        }

        Span<ulong> accumulator = stackalloc ulong[Lanes];
        _one.CopyTo(accumulator);

        for (int i = 0; i < exponentBigEndian.Length; i++)
        {
            byte current = exponentBigEndian[i];

            // Most significant window of the byte first.
            for (int w = 0; w < windowsPerByte; w++)
            {
                int shift = 8 - windowBits * (w + 1);
                int digit = (current >> shift) & (windowSize - 1);

                for (int square = 0; square < windowBits; square++)
                {
                    Multiply(accumulator, accumulator, accumulator);
                }

                Multiply(accumulator, window.Slice(digit * Lanes, Lanes), accumulator);
            }
        }

        accumulator.CopyTo(result);
    }

    /// <summary>
    /// The final, sequential carry pass of a multiplication: every lane is reduced to a 29-bit digit
    /// and its excess added to the next. The lanes are below 2^36 after the last normalization, so
    /// nothing overflows, and the value is below 2p, so nothing carries out of the top lane.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PropagateCarries(ref ulong lanes)
    {
        ulong carry = 0;
        for (int k = 0; k < Lanes; k++)
        {
            ulong value = Unsafe.Add(ref lanes, k) + carry;
            Unsafe.Add(ref lanes, k) = value & DigitMask;
            carry = value >> DigitBits;
        }
    }

    private static ulong[] ToDigits(BigInteger value)
    {
        ulong[] digits = new ulong[Lanes];
        WriteDigits(value, digits);
        return digits;
    }

    /// <summary>
    /// Writes a non-negative value below 2^(29 * 144) as <see cref="Lanes"/> 29-bit digits, least
    /// significant first, by way of the 64-bit limbs <see cref="MontgomeryContext"/> already knows
    /// how to produce on either endianness.
    /// </summary>
    internal static void WriteDigits(BigInteger value, Span<ulong> digits)
    {
        if (value.Sign < 0 || value.GetBitLength() > DigitBits * Lanes)
        {
            throw new ArgumentOutOfRangeException(nameof(value), "Value does not fit in the digit representation.");
        }

        Span<ulong> limbs = stackalloc ulong[LimbsForDigits];
        MontgomeryContext.WriteLimbs(value, limbs, !BitConverter.IsLittleEndian);
        for (int k = 0; k < Lanes; k++)
        {
            int bit = k * DigitBits;
            int limb = bit >> 6;
            int offset = bit & 63;
            ulong digit = limbs[limb] >> offset;
            if (offset + DigitBits > 64)
            {
                digit |= limbs[limb + 1] << (64 - offset);
            }

            digits[k] = digit & DigitMask;
        }
    }

    /// <summary>Reads a fully carried digit vector (every digit below 2^29) back as an integer.</summary>
    internal static BigInteger FromDigits(ReadOnlySpan<ulong> digits)
    {
        Span<ulong> limbs = stackalloc ulong[LimbsForDigits];
        limbs.Clear();
        for (int k = 0; k < Lanes; k++)
        {
            int bit = k * DigitBits;
            int limb = bit >> 6;
            int offset = bit & 63;
            ulong digit = digits[k];
            limbs[limb] |= digit << offset;
            if (offset + DigitBits > 64)
            {
                limbs[limb + 1] |= digit >> (64 - offset);
            }
        }

        return MontgomeryContext.FromLimbs(limbs);
    }
}
