namespace ElectionGuard.Core.UnitTests.RecordFormat;

/// <summary>Paths of the committed conformance artifacts under test/egrf/ (design §5.7).</summary>
internal static class EgrfTestFiles
{
    public static string RepositoryRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory != null && !File.Exists(Path.Combine(directory.FullName, "electionguard-cs.sln")))
        {
            directory = directory.Parent;
        }

        return directory?.FullName ?? throw new InvalidOperationException("The repository root (electionguard-cs.sln) is not above the test binaries.");
    }

    /// <summary>test/egrf/vectors/<paramref name="name"/>.</summary>
    public static string Vector(string name) => Path.Combine(RepositoryRoot(), "test", "egrf", "vectors", name);

    /// <summary>Reads a committed text file with LF line endings (a checkout may convert them).</summary>
    public static string ReadText(string path) => File.ReadAllText(path).Replace("\r\n", "\n");

    /// <summary>
    /// Compares <paramref name="generated"/> with the committed file at <paramref name="path"/>, or,
    /// when the environment variable <paramref name="writeVariable"/> is "1", writes it first. The
    /// committed vectors are generated by the tests themselves and reviewed as a diff.
    /// </summary>
    public static void AssertCommitted(string path, string generated, string writeVariable)
    {
        if (Environment.GetEnvironmentVariable(writeVariable) == "1")
        {
            Directory.CreateDirectory(Path.GetDirectoryName(path)!);
            File.WriteAllText(path, generated);
        }

        Assert.True(File.Exists(path), $"{path} is missing; run the tests with {writeVariable}=1 to create it.");
        Assert.Equal(generated, ReadText(path));
    }
}
