#!/usr/bin/env python3
"""Generates src/ElectionGuard.Core/Crypto/Avx512Montgomery.Kernel.g.cs.

The AVX-512 almost-Montgomery multiplication keeps its 144-digit accumulator in 18 Vector512<ulong>
values. Written as a loop over a span, the JIT loads and stores every one of them on every one of
the 142 iterations; written as 18 named locals it can keep them in zmm registers (there are 32),
which is what makes the kernel worth having. C# has no way to say "unroll this over 18 locals", so
the unrolled body is generated here rather than maintained by hand.

Everything that is arithmetic rather than repetition - the digit width, iteration count, the
normalization interval and the bounds that justify them - lives in the hand-written
Avx512Montgomery.cs. This script only emits the per-vector repetition, and the generated code
refers back to those constants by name.

Run from the repository root:

    python tools/generate_avx512_montgomery_kernel.py

and commit the regenerated file. Pass --check to fail (exit 1) instead of writing when the
committed file is out of date.
"""

import pathlib
import sys

# Must equal Avx512Montgomery.Vectors (Lanes / 8). The generated file asserts this at compile time
# through a const it declares and the hand-written half checks.
VECTORS = 18

OUTPUT = pathlib.Path(__file__).resolve().parent.parent / "src" / "ElectionGuard.Core" / "Crypto" / "Avx512Montgomery.Kernel.g.cs"


def generate() -> str:
    n = VECTORS
    lines: list[str] = []
    emit = lines.append

    emit("// <auto-generated>")
    emit("//     Generated by tools/generate_avx512_montgomery_kernel.py. Do not edit by hand.")
    emit("//     To regenerate, run from the repository root:")
    emit("//         python tools/generate_avx512_montgomery_kernel.py")
    emit("// </auto-generated>")
    emit("")
    emit("using System.Runtime.CompilerServices;")
    emit("using System.Runtime.Intrinsics;")
    emit("using System.Runtime.Intrinsics.X86;")
    emit("")
    emit("namespace ElectionGuard.Core.Crypto;")
    emit("")
    emit("internal sealed partial class Avx512Montgomery")
    emit("{")
    emit("    /// <summary>The vector count this kernel was generated for; must equal <see cref=\"Vectors\"/>.</summary>")
    emit(f"    private const int GeneratedVectors = {n};")
    emit("")
    emit("    /// <summary>")
    emit("    /// The body of <see cref=\"Multiply\"/>, with the accumulator unrolled into named locals so that")
    emit("    /// it can stay in registers. See the class remarks for the algorithm and its bounds.")
    emit("    /// </summary>")
    emit("    [MethodImpl(MethodImplOptions.NoInlining)]")
    emit("    private void MultiplyCore(ref ulong a, ref ulong b, ref ulong result)")
    emit("    {")
    emit("        ref Vector512<ulong> va = ref Unsafe.As<ulong, Vector512<ulong>>(ref a);")
    emit("        ref Vector512<ulong> vm = ref Unsafe.As<ulong, Vector512<ulong>>(ref _modulusDigits[0]);")
    emit("        ulong a0 = a;")
    emit("        ulong m0 = _modulusDigits[0];")
    emit("        ulong k0 = _k0;")
    emit("        Vector512<ulong> zero = Vector512<ulong>.Zero;")
    emit("        Vector512<ulong> mask = Vector512.Create(DigitMask);")
    emit("")
    emit("        // The accumulator, digit 8k + j in lane j of xk.")
    for k in range(n):
        emit(f"        Vector512<ulong> x{k} = zero;")
    emit("")
    emit("        int i = 0;")
    emit("        for (int block = 0; block < Iterations; block += NormalizeInterval)")
    emit("        {")
    emit("            int end = Math.Min(block + NormalizeInterval, Iterations);")
    emit("            for (; i < end; i++)")
    emit("            {")
    emit("                // y makes the bottom digit of acc + a*b[i] + y*p divisible by 2^DigitBits, so the")
    emit("                // whole sum can be shifted down one digit. That bottom digit's high part is the")
    emit("                // carry, computed here in scalar because the shift discards lane 0.")
    emit("                ulong bi = Unsafe.Add(ref b, i);")
    emit("                ulong t0 = x0.ToScalar() + a0 * bi;")
    emit("                ulong y = unchecked(t0 * k0) & DigitMask;")
    emit("                ulong carry = (t0 + y * m0) >> DigitBits;")
    emit("                Vector512<uint> vb = Vector512.Create(bi).AsUInt32();")
    emit("                Vector512<uint> vy = Vector512.Create(y).AsUInt32();")
    emit("")
    emit("                // acc += a * b[i] + p * y, each lane a 32x32->64-bit product of two digits.")
    for k in range(n):
        emit(
            f"                Vector512<ulong> s{k} = Avx512F.Add(Avx512F.Add(x{k}, "
            f"Avx512F.Multiply(Unsafe.Add(ref va, {k}).AsUInt32(), vb)), "
            f"Avx512F.Multiply(Unsafe.Add(ref vm, {k}).AsUInt32(), vy));"
        )
    emit("")
    emit("                // acc >>= DigitBits: every lane moves down one, and the top lane fills with zero.")
    for k in range(n - 1):
        emit(f"                x{k} = Avx512F.AlignRight64(s{k + 1}, s{k}, 1);")
    emit(f"                x{n - 1} = Avx512F.AlignRight64(zero, s{n - 1}, 1);")
    emit("                x0 = Avx512F.Add(x0, Vector512.CreateScalar(carry));")
    emit("            }")
    emit("")
    emit("            // One carry step for every lane at once: lane k keeps its low DigitBits bits and gains")
    emit("            // lane k-1's high bits.")
    for k in range(n):
        emit(f"            Vector512<ulong> h{k} = Avx512F.ShiftRightLogical(x{k}, DigitBits);")
    emit("            x0 = Avx512F.Add(Avx512F.And(x0, mask), Avx512F.AlignRight64(h0, zero, 7));")
    for k in range(1, n):
        emit(f"            x{k} = Avx512F.Add(Avx512F.And(x{k}, mask), Avx512F.AlignRight64(h{k}, h{k - 1}, 7));")
    emit("        }")
    emit("")
    emit("        // a and b are not read again, so writing the result now is safe even when it aliases them.")
    emit("        ref Vector512<ulong> vr = ref Unsafe.As<ulong, Vector512<ulong>>(ref result);")
    for k in range(n):
        emit(f"        Unsafe.Add(ref vr, {k}) = x{k};")
    emit("")
    emit("        PropagateCarries(ref result);")
    emit("    }")
    emit("}")
    return "\r\n".join(lines) + "\r\n"


def main() -> int:
    content = generate()
    if "--check" in sys.argv[1:]:
        current = OUTPUT.read_bytes().decode("utf-8") if OUTPUT.exists() else ""
        if current != content:
            print(f"{OUTPUT} is out of date; run python tools/generate_avx512_montgomery_kernel.py", file=sys.stderr)
            return 1
        return 0

    OUTPUT.write_bytes(content.encode("utf-8"))
    print(f"Wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
